// ---------------------------- AUTO GENERATED FILE ----------------------------
// This file contains references to all centralized data files in the project
// It serves as a single source of truth for data access patterns and file locations
// Do not edit this file directly, it is auto-generated from the data files

export const dataFiles = {
  // SINGLE SOURCES OF TRUTH
  
  // Primary blog data source - contains ALL blog information including contentLink
  blogData: "@/app/_data/_blogs-details.js",
  
  // Primary events data source - contains ALL event information  
  eventsData: "@/app/_data/_eventsData.js",
  
  // COMPONENT-SPECIFIC DATA
  
  // Home page specific data (stats, quotes) - excludes blogs/events
  homePageData: "@/app/_data/_homeData.js",
  
  // Navigation data for all navigation components
  navigationData: "@/app/_data/_navigationData.js",
  
  // Footer links and contact information
  footerData: "@/app/_data/_footerData.js",
  
  // Resources page data
  resourcesData: "@/app/_data/_resourcesData.js",
  
  // Leaderboard page data - coding competition rankings
  leaderboardData: "@/app/_data/_leaderboardData.js",
  
  
  // COMPATIBILITY LAYER
  
  // Re-exports blog data in legacy format for existing components
  sampleArticles: "@/app/_data/_sampleArticles.ts",
  
  // EXISTING DATA FILES (preserved)
  aboutUs: "@/app/_data/_aboutUs.js",
  adminPage: "@/app/_data/_adminPage.js", 
  hallOfFameData: "@/app/_data/_hallOfFameData.js",
  ourTeamPage: "@/app/_data/_ourTeamPage.js",
  sidebar: "@/app/_data/_sidebar.js",
};

// DATA ACCESS PATTERNS
export const dataAccessPatterns = {
  // For home page content - automatically gets most recent
  homePageBlogs: "getRecentBlogs(3) from _blogs-details.js",
  homePageEvents: "getRecentEvents(3) from _eventsData.js",
  
  // For blogs page - gets all blogs
  allBlogs: "blogPosts from _blogs-details.js",
  
  // For events page - gets all events  
  allEvents: "eventsData from _eventsData.js",
  
  // For blog detail page - gets specific blog + contentLink
  blogDetail: "getBlogById(id) from _blogs-details.js",
  
  // For event detail page - gets specific event
  eventDetail: "getEventById(id) from _eventsData.js",
  
  // For leaderboard page - gets all rankings and stats
  leaderboardRankings: "leaderboardData from _leaderboardData.js",
  leaderboardTopPerformers: "getTopPerformers(5) from _leaderboardData.js"
};

// Helper functions available
export const helperFunctions = {
  // Blog helpers
  "getRecentBlogs(count)": "Get most recent blogs sorted by date",
  "getFeaturedBlogs()": "Get all featured blogs",
  "getBlogById(id)": "Get specific blog by ID",
  "getBlogsByCategory(category)": "Get blogs by category",
  "getBlogsByTag(tag)": "Get blogs by tag",
  
  // Event helpers  
  "getRecentEvents(count)": "Get most recent events sorted by date",
  "getUpcomingEvents()": "Get all upcoming events",
  "getCompletedEvents()": "Get all completed events", 
  "getFeaturedEvents()": "Get high priority events",
  "getEventById(id)": "Get specific event by ID",
  
  // Leaderboard helpers
  "getTopPerformers(count)": "Get top performers by score",
  "getLeaderboardByCategory(category)": "Get rankings by category (algorithms, datastructures, contests, problems)",
  "getMemberById(id)": "Get specific member data by ID",
  "getRecentActivity()": "Get recent coding activity across all members",
  "getTopLanguages()": "Get most popular programming languages"
};

// Components updated to use centralized data:
export const updatedComponents = [
  "src/components/home/recent-events-section.tsx - now uses getRecentEvents()",
  "src/components/home/featured-blogs.tsx - now uses getRecentBlogs()",
  "src/app/page.tsx - now uses getRecentBlogs() for fallback data",
  "src/app/blogs/page.tsx - now uses blogPosts from _blogs-details.js",
  "src/app/_data/_sampleArticles.ts - now re-exports from _blogs-details.js",
  "src/app/leaderboard/page.tsx - now uses leaderboardData with coding/DS theme",
  
  // Previously updated components  
  "src/components/home/about-section.tsx",
  "src/components/home/quotes-section.tsx", 
  "src/components/layout/footer.tsx",
  "src/components/layout/navbar.tsx",
  "src/components/navigation.tsx",
  "src/components/sidebar/Sidebar.tsx",
  "src/components/resources/resource-cards.tsx"
];
